id: IF7A04537
initial_creation_type: ebook
source_metadata:
  id: RDI-SS-14
  title: རིགས་ལམ་ནོར་བུའི་བང་མཛོད་ཀྱི་སྒོ་བརྒྱ་འབྱེད་པའི་འཕྲུལ་གྱི་ལྡི་མིག།
  author: མཛད་པ་པོ། ཞྭ་དམར་དྲུག་པ་ཆོས་ཀྱི་དབང་ཕྱུག།, མཛད་པ་པོ། གུང་ཐང་བློ་གྲོས་རྒྱ་མཚོ།
  authors: &id001
  - མཛད་པ་པོ། ཞྭ་དམར་དྲུག་པ་ཆོས་ཀྱི་དབང་ཕྱུག།
  - མཛད་པ་པོ། གུང་ཐང་བློ་གྲོས་རྒྱ་མཚོ།
  sku: RDI-SS-14
  cover: Book_14_Cover.jpg
  volume: {}
  series: བློ་གྲོས་མཐའ་ཡས་པའི་མཛོད།
  title_source: epub:dc:title:ambiguous-layer
ebook_metadata:
  title: རིགས་ལམ་ནོར་བུའི་བང་མཛོད་ཀྱི་སྒོ་བརྒྱ་འབྱེད་པའི་འཕྲུལ་གྱི་ལྡི་མིག།
  authors: *id001
  sku: RDI-SS-14
  cover: Book_14_Cover.jpg
layers:
- Author
- BookNumber
- BookTitle
- Chapter
- Citation
- Commentary
- Footnote
- Sabche
- Tsawa
